# Generated by Django 5.2.12 on 2026-04-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='api.mission'),
        ),
    ]
