# Generated by Django 5.2.12 on 2026-04-09 08:15

from django.db import migrations, models


def promote_existing_admin_profiles(apps, schema_editor):
    AccountProfile = apps.get_model("api", "AccountProfile")
    User = apps.get_model("auth", "User")

    admin_user_ids = User.objects.filter(
        models.Q(is_staff=True) | models.Q(is_superuser=True)
    ).values_list("id", flat=True)

    AccountProfile.objects.filter(user_id__in=admin_user_ids).update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_slot_mission_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('client', 'Client'), ('admin', 'Admin')], default='freelance', max_length=20),
        ),
        migrations.RunPython(
            promote_existing_admin_profiles, migrations.RunPython.noop
        ),
    ]
